### ISSUE TITLE
Duplicate user lines in /etc/sudoers

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/atmosphere-ansible#26]
/etc/sudoers
```
my_username  ALL = (ALL) NOPASSWD: ALL
%users ALL=(ALL) NOPASSWD: ALL
my_username ALL=(ALL) NOPASSWD:ALL
my_username  ALL=(ALL) ALL
```

This probably could be solved with a blockinfile.

**Comment by nfaction** [comment]
To fix this, we are now removing all entries for `my_username` and re-adding it afterwards.  The variables have now been moved into `group_vars` and can be then modified for each cloud, based on their preferred configuration.  We also now have a way to remove opposite methods of deploys from their respective clouds.  For instance, clouds that prefer `NOPASSWD` will remove `ALL` directives and visa versa.
