### ISSUE TITLE
SSHKEYS once added cannot be removed by a user

### ISSUE THREAD

**Issue by cdosborn** [iPlantCollaborativeOpenSource/atmosphere-ansible#41]
1. A user adds a friend's key to their box in atmosphere
2. User redeploys and see's friend's key
3. Friend goes hostile
4. User removes key from atmosphere and redeploys
5. Friend still has access, and makes user 😞

**Comment by amercer1** [comment]
> User removes key and redeploys

How is the user removing the key? On the instance? From the ssh advance settings on troposphere?

**Comment by cdosborn** [comment]
Through the ui

**Comment by steve-gregory** [comment]
We would probably be best served by handling this as a "User customization" playbook, to remove all "non-authorized" ssh keys from a users home directory. Troposphere would have a corresponding option made available to end-users through the UI, and this could be handled in an as-needed basis.

**Comment by cdosborn** [comment]
This issue has been addressed here:
https://pods.iplantcollaborative.org/jira/browse/ATMO-1473

No changes necessary to atmosphere-ansible
